### Регистрация
POST https://weblybackend.onrender.com/api/auth/register
Content-Type: application/json

{
    "name": "Zoow",
    "password": "Zoow",
    "email": "Zoow@example.com"
}

### Логин
POST https://weblybackend.onrender.com/api/auth/login
Content-Type: application/json

{
    "email": "Zoow@example.com",
    "password": "Zoow"
}

### Сохранение данных
POST http://localhost:5259/api/sitedata
Content-Type: application/json

{
    "data": "{\"title\": \"My Site\", \"content\": \"Welcome to my site!\"}"
}

### Проверка состояния базы данных
GET http://localhost:5259/api/auth/check

### Проверка состояния базы данных
GET https://weblybackend.onrender.com/api/auth/check

